base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  os:
    name: ubi
    namespace: ocp
    tag: "8"
images:
  - dockerfile_literal: |
      FROM quay.io/strimzi-qe/strimzi-tests:release-0.32.x
      WORKDIR /tmp/tests
      CMD ["/bin/bash"]
    to: test-image
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: latest
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      GROUPS: acceptance
      OLM_OPERATOR_VERSION: 2.3.0-1
    test:
      - ref: amq-streams-run-tests
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: amq-streams-ocp4.13-lp-interop
