base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  os:
    name: ubi
    namespace: ocp
    tag: "8"
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
  - as: latest
    cron: 0 1 * * 1
    steps:
      cluster_profile: aws-cspi-qe
      test:
        - ref: strimzi-run-tests
      env:
        BASE_DOMAIN: aws.interop.ccitredhat.com
        SPOT_INSTANCES: "true"
        GROUPS: acceptance
        OLM_OPERATOR_VERSION: 2.3.0-1
        OLM_OPERATOR_CHANNEL: stable
      from: quay.io/strimzi-qe/strimzi-tests:release-0.32.x
      workflow: ipi-aws
  - as: lts-2-2
    cron: 0 1 * * 1
    steps:
      cluster_profile: aws-cspi-qe
      test:
        - ref: strimzi-run-tests
      env:
        BASE_DOMAIN: aws.interop.ccitredhat.com
        SPOT_INSTANCES: "true"
        GROUPS: acceptance
        OLM_OPERATOR_VERSION: 2.2.0-5
        OLM_OPERATOR_CHANNEL: amq-streams-2.2.x
      from: quay.io/strimzi-qe/strimzi-tests:release-0.29.x
      workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: strimzi
  repo: strimzi-kafka-operator
  variant: amq-streams-ocp4.13-lp-interop
