base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  os:
    name: ubi
    namespace: ocp
    tag: "8"
  test-image:
    name: strimzi-tests
    namespace: ci
    tag: release-0.29.x
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: amq-streams-2-2
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      GROUPS: sanity
      OLM_OPERATOR_CHANNEL: amq-streams-2.2.x
    test:
    - ref: strimzi-run-tests
    workflow: ipi-aws
zz_generated_metadata:
  branch: release-0.29.x
  org: amq-streams-qe
  repo: strimzi-kafka-operator
  variant: amq-streams-ocp4.13-lp-interop
