base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- from: quay.io/strimzi-qe/strimzi-tests:release-0.32.x
  to: test-image
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: amq-streams-2.3
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      GROUPS: acceptance
      OLM_OPERATOR_CHANNEL: stable
      OLM_OPERATOR_VERSION: 2.3.0-1
      SPOT_INSTANCES: "true"
    test:
    - ref: strimzi-run-tests
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: amq-streams-qe
  repo: strimzi-kafka-operator
  variant: amq-streams-ocp4.13-lp-interop
